# Refining data (Data Wrangling)

In [1]:
# Importing Libraries

import pandas as pd
import numpy as np
from collections import Counter

In [2]:
raw_data = pd.read_csv("raw_data_set.csv")

In [3]:
raw_data

,institution_name,title_of_course,star_ratings,number_of_raters,skills_list,level_of_course
0,University of Pennsylvania,English for Career Development,4.8,(15K reviews),"Skills you'll gain: Business Communication, Cr...",Mixed · Course · 1 - 3 Months
1,École Polytechnique,Étudier en France: French Intermediate course ...,4.8,(4.7K reviews),"Skills you'll gain: Communication, Culture, Wr...",Intermediate · Course · 1 - 3 Months
2,Yonsei University,First Step Korean,4.9,(49K reviews),"Skills you'll gain: Communication, Culture, Wr...",Beginner · Course · 1 - 3 Months
3,Georgia Institute of Technology,Lesson | Small Talk & Conversational Vocabulary,4.2,(956 reviews),NaN,Mixed · Course · 1 - 4 Weeks
4,Peking University,Chinese for Beginners,4.8,(19K reviews),Skills you'll gain: Communication,Mixed · Course · 1 - 3 Months
...,...,...,...,...,...,...
206,Arizona State University,商务英语课程:财经英语 Finance & Economics,4.8,(10 reviews),Skills you'll gain: Leadership and Management,Intermediate · Course · 1 - 3 Months
207,"University of California, Irvine",Teaching Intermediate Grammar Project,4.4,(10 reviews),NaN,Intermediate · Course · 1 - 3 Months
208,Arizona State University,Proyecto Final: Chino básico - Lenguaje y cult...,4.4,(7 reviews),NaN,Mixed · Course · 1 - 3 Months
209,Arizona State University,总计划案 Final Project,NaN,NaN,NaN,Intermediate · Course · 1 - 3 Months
210,Arizona State University,Chino básico: Lenguaje y cultura empresarial,4.5,(508 reviews),"Skills you'll gain: Culture, Algebra, Calculus...",Beginner · Specialization · 3 - 6 Months

In [4]:
raw_data.isnull().sum()

institution_name     0
title_of_course      0
star_ratings        15
number_of_raters    15
skills_list         93
level_of_course      0
dtype: int64

In [5]:
raw_data.shape

(211, 6)

## Creating a refined data set from the raw data set

In [6]:
refined_data = pd.DataFrame()

In [7]:
refined_data["institution_name"] = raw_data["institution_name"]

In [8]:
refined_data["title_of_course"] = raw_data["title_of_course"]

In [9]:
refined_data.head()

,institution_name,title_of_course
0,University of Pennsylvania,English for Career Development
1,École Polytechnique,Étudier en France: French Intermediate course ...
2,Yonsei University,First Step Korean
3,Georgia Institute of Technology,Lesson | Small Talk & Conversational Vocabulary
4,Peking University,Chinese for Beginners

In [10]:
refined_data.shape

(211, 2)

In [11]:
refined_data["star_ratings"] = raw_data["star_ratings"]

In [12]:
refined_data.head()

,institution_name,title_of_course,star_ratings
0,University of Pennsylvania,English for Career Development,4.8
1,École Polytechnique,Étudier en France: French Intermediate course ...,4.8
2,Yonsei University,First Step Korean,4.9
3,Georgia Institute of Technology,Lesson | Small Talk & Conversational Vocabulary,4.2
4,Peking University,Chinese for Beginners,4.8

## Replacing the null values in star_ratings with the average of the whole column.

In [13]:
star_avg = refined_data["star_ratings"].mean()

In [14]:
star_avg = round(star_avg, 1)

In [15]:
star_avg

4.7

In [16]:
refined_data["star_ratings"] = refined_data["star_ratings"].fillna(star_avg)

In [17]:
refined_data

,institution_name,title_of_course,star_ratings
0,University of Pennsylvania,English for Career Development,4.8
1,École Polytechnique,Étudier en France: French Intermediate course ...,4.8
2,Yonsei University,First Step Korean,4.9
3,Georgia Institute of Technology,Lesson | Small Talk & Conversational Vocabulary,4.2
4,Peking University,Chinese for Beginners,4.8
...,...,...,...
206,Arizona State University,商务英语课程:财经英语 Finance & Economics,4.8
207,"University of California, Irvine",Teaching Intermediate Grammar Project,4.4
208,Arizona State University,Proyecto Final: Chino básico - Lenguaje y cult...,4.4
209,Arizona State University,总计划案 Final Project,4.7
210,Arizona State University,Chino básico: Lenguaje y cultura empresarial,4.5

In [18]:
refined_data.isnull().sum()

institution_name    0
title_of_course     0
star_ratings        0
dtype: int64

## Adding the number of raters column and creating its proper format.

In [19]:
number_of_raters = []

In [20]:
refined_data["number_of_raters"] = raw_data["number_of_raters"]

In [21]:
refined_data["number_of_raters"].head()

0     (15K reviews)
1    (4.7K reviews)
2     (49K reviews)
3     (956 reviews)
4     (19K reviews)
Name: number_of_raters, dtype: object

In [22]:
refined_data["number_of_raters"] = refined_data["number_of_raters"].str.lstrip('(')

In [23]:
refined_data["number_of_raters"] = refined_data["number_of_raters"].str.rstrip('reviews)')

In [24]:
refined_data["number_of_raters"]

0       15K
1      4.7K
2       49K
3       956
4       19K
       ...
206      10
207      10
208       7
209      NaN
210     508
Name: number_of_raters, Length: 211, dtype: object

In [25]:
print(type(refined_data["number_of_raters"].iloc[0]))

<class 'str'>

In [26]:
refined_data['number_of_raters'] = refined_data['number_of_raters'].astype(str).str.rstrip('K ').astype(float) * 1000

In [27]:
refined_data["number_of_raters"]

0       15000.0
1        4700.0
2       49000.0
3      956000.0
4       19000.0
         ...
206     10000.0
207     10000.0
208      7000.0
209         NaN
210    508000.0
Name: number_of_raters, Length: 211, dtype: float64

In [28]:
refined_data

,institution_name,title_of_course,star_ratings,number_of_raters
0,University of Pennsylvania,English for Career Development,4.8,15000.0
1,École Polytechnique,Étudier en France: French Intermediate course ...,4.8,4700.0
2,Yonsei University,First Step Korean,4.9,49000.0
3,Georgia Institute of Technology,Lesson | Small Talk & Conversational Vocabulary,4.2,956000.0
4,Peking University,Chinese for Beginners,4.8,19000.0
...,...,...,...,...
206,Arizona State University,商务英语课程:财经英语 Finance & Economics,4.8,10000.0
207,"University of California, Irvine",Teaching Intermediate Grammar Project,4.4,10000.0
208,Arizona State University,Proyecto Final: Chino básico - Lenguaje y cult...,4.4,7000.0
209,Arizona State University,总计划案 Final Project,4.7,NaN
210,Arizona State University,Chino básico: Lenguaje y cultura empresarial,4.5,508000.0

In [29]:
raters_avg = refined_data["number_of_raters"].mean()

In [30]:
raters_avg

193730.61224489796

In [31]:
# here I have interpolated the values instead of just replacing the null values by the average.
refined_data["number_of_raters"] = refined_data["number_of_raters"].interpolate()

In [32]:
refined_data["number_of_raters"]

0       15000.0
1        4700.0
2       49000.0
3      956000.0
4       19000.0
         ...
206     10000.0
207     10000.0
208      7000.0
209    257500.0
210    508000.0
Name: number_of_raters, Length: 211, dtype: float64

In [33]:
refined_data

,institution_name,title_of_course,star_ratings,number_of_raters
0,University of Pennsylvania,English for Career Development,4.8,15000.0
1,École Polytechnique,Étudier en France: French Intermediate course ...,4.8,4700.0
2,Yonsei University,First Step Korean,4.9,49000.0
3,Georgia Institute of Technology,Lesson | Small Talk & Conversational Vocabulary,4.2,956000.0
4,Peking University,Chinese for Beginners,4.8,19000.0
...,...,...,...,...
206,Arizona State University,商务英语课程:财经英语 Finance & Economics,4.8,10000.0
207,"University of California, Irvine",Teaching Intermediate Grammar Project,4.4,10000.0
208,Arizona State University,Proyecto Final: Chino básico - Lenguaje y cult...,4.4,7000.0
209,Arizona State University,总计划案 Final Project,4.7,257500.0
210,Arizona State University,Chino básico: Lenguaje y cultura empresarial,4.5,508000.0

## Adding the level_of_course column and creatin its proper format.

In [34]:
refined_data["level_of_course"] = raw_data["level_of_course"]

In [35]:
refined_data["level_of_course"]

0                 Mixed · Course · 1 - 3 Months
1          Intermediate · Course · 1 - 3 Months
2              Beginner · Course · 1 - 3 Months
3                  Mixed · Course · 1 - 4 Weeks
4                 Mixed · Course · 1 - 3 Months
                         ...
206        Intermediate · Course · 1 - 3 Months
207        Intermediate · Course · 1 - 3 Months
208               Mixed · Course · 1 - 3 Months
209        Intermediate · Course · 1 - 3 Months
210    Beginner · Specialization · 3 - 6 Months
Name: level_of_course, Length: 211, dtype: object

In [36]:
refined_data[['level', 'waste', 'duration']] = refined_data['level_of_course'].str.split('·', expand=True)

In [37]:
refined_data

,institution_name,title_of_course,star_ratings,number_of_raters,level_of_course,level,waste,duration
0,University of Pennsylvania,English for Career Development,4.8,15000.0,Mixed · Course · 1 - 3 Months,Mixed,Course,1 - 3 Months
1,École Polytechnique,Étudier en France: French Intermediate course ...,4.8,4700.0,Intermediate · Course · 1 - 3 Months,Intermediate,Course,1 - 3 Months
2,Yonsei University,First Step Korean,4.9,49000.0,Beginner · Course · 1 - 3 Months,Beginner,Course,1 - 3 Months
3,Georgia Institute of Technology,Lesson | Small Talk & Conversational Vocabulary,4.2,956000.0,Mixed · Course · 1 - 4 Weeks,Mixed,Course,1 - 4 Weeks
4,Peking University,Chinese for Beginners,4.8,19000.0,Mixed · Course · 1 - 3 Months,Mixed,Course,1 - 3 Months
...,...,...,...,...,...,...,...,...
206,Arizona State University,商务英语课程:财经英语 Finance & Economics,4.8,10000.0,Intermediate · Course · 1 - 3 Months,Intermediate,Course,1 - 3 Months
207,"University of California, Irvine",Teaching Intermediate Grammar Project,4.4,10000.0,Intermediate · Course · 1 - 3 Months,Intermediate,Course,1 - 3 Months
208,Arizona State University,Proyecto Final: Chino básico - Lenguaje y cult...,4.4,7000.0,Mixed · Course · 1 - 3 Months,Mixed,Course,1 - 3 Months
209,Arizona State University,总计划案 Final Project,4.7,257500.0,Intermediate · Course · 1 - 3 Months,Intermediate,Course,1 - 3 Months
210,Arizona State University,Chino básico: Lenguaje y cultura empresarial,4.5,508000.0,Beginner · Specialization · 3 - 6 Months,Beginner,Specialization,3 - 6 Months

In [38]:
# here I have dropped the unwanted columns in the data frame.

refined_data.drop(["level_of_course", "waste"], axis=1, inplace=True)

In [39]:
refined_data

,institution_name,title_of_course,star_ratings,number_of_raters,level,duration
0,University of Pennsylvania,English for Career Development,4.8,15000.0,Mixed,1 - 3 Months
1,École Polytechnique,Étudier en France: French Intermediate course ...,4.8,4700.0,Intermediate,1 - 3 Months
2,Yonsei University,First Step Korean,4.9,49000.0,Beginner,1 - 3 Months
3,Georgia Institute of Technology,Lesson | Small Talk & Conversational Vocabulary,4.2,956000.0,Mixed,1 - 4 Weeks
4,Peking University,Chinese for Beginners,4.8,19000.0,Mixed,1 - 3 Months
...,...,...,...,...,...,...
206,Arizona State University,商务英语课程:财经英语 Finance & Economics,4.8,10000.0,Intermediate,1 - 3 Months
207,"University of California, Irvine",Teaching Intermediate Grammar Project,4.4,10000.0,Intermediate,1 - 3 Months
208,Arizona State University,Proyecto Final: Chino básico - Lenguaje y cult...,4.4,7000.0,Mixed,1 - 3 Months
209,Arizona State University,总计划案 Final Project,4.7,257500.0,Intermediate,1 - 3 Months
210,Arizona State University,Chino básico: Lenguaje y cultura empresarial,4.5,508000.0,Beginner,3 - 6 Months

In [40]:
refined_data["duration"].unique()

array([' 1 - 3 Months', ' 1 - 4 Weeks', ' 3 - 6 Months'], dtype=object)

## Here I am adding the most crucial column and creating its proper format.

In [41]:
refined_data["skills_list"] = raw_data["skills_list"]

In [42]:
refined_data["skills_list"]

0      Skills you'll gain: Business Communication, Cr...
1      Skills you'll gain: Communication, Culture, Wr...
2      Skills you'll gain: Communication, Culture, Wr...
3                                                    NaN
4                      Skills you'll gain: Communication
                             ...
206        Skills you'll gain: Leadership and Management
207                                                  NaN
208                                                  NaN
209                                                  NaN
210    Skills you'll gain: Culture, Algebra, Calculus...
Name: skills_list, Length: 211, dtype: object

In [43]:
refined_data.isnull().sum()

institution_name     0
title_of_course      0
star_ratings         0
number_of_raters     0
level                0
duration             0
skills_list         93
dtype: int64

In [44]:
refined_data.shape[0]

211

In [45]:
# as we can see here the percentage of null values here is 44% so we need to handle it properly.

percentage = (93/211)*100

In [46]:
percentage

44.07582938388626

In [47]:
refined_data["skills_list"] = refined_data["skills_list"].str.lstrip("Skills you'll gain:")

In [48]:
# As we cannot interpolate the rows as it is text data we will just copy the upper row in the null row for skills.

refined_data['skills_list'].ffill(inplace=True)

In [49]:
skills = []
for _, row in refined_data.iterrows():
    if pd.notna(row['skills_list']):  # Check for NaN values
        skills.extend(row['skills_list'].split(', '))

In [50]:
skills

['Business Communication',
 'Critical Thinking',
 'Human Resources',
 'Human Resources Operations',
 'Application Development',
 'People Management',
 'Communication',
 'Culture',
 'Writing',
 'Communication',
 'Culture',
 'Writing',
 'Communication',
 'Culture',
 'Writing',
 'Communication',
 'Communication',
 'Communication',
 'Writing',
 'Culture',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Business Communication',
 'Writing',
 'Research and Design',
 'Visual Design',
 'Communication',
 'Business Communication',
 'Writing',
 'Research and Design',
 'Visual Design',
 'Communication',
 'Business Communication',
 'Writing',
 'Research and Design',
 'Visual Design',
 'Writing',
 'Communication',
 'Culture',
 'Writing',
 'Business Communication',
 'Communication',
 'Leadership and Management',
 'Planning',
 'Negotiation',
 'Writing',
 'People Management',
 'Professional Development',
 'Business Intelligence',
 'Strategy',
 'Business Development',
 'Decision Making',
 'Organizational Development',
 'Project Management',
 'Public Relations',
 'People Analysis',
 'Customer Relationship Management',
 'Basic Descriptive Statistics',
 'Data Analysis',
 'Human Resources',
 'Collaboration',
 'Visualization (Computer Graphics)',
 'Data Visualization',
 'Statistical Tests',
 'Business Communication',
 'Communication',
 'Leadership and Management',
 'Planning',
 'Negotiation',
 'Writing',
 'People Management',
 'Professional Development',
 'Business Intelligence',
 'Strategy',
 'Business Development',
 'Decision Making',
 'Organizational Development',
 'Project Management',
 'Public Relations',
 'People Analysis',
 'Customer Relationship Management',
 'Basic Descriptive Statistics',
 'Data Analysis',
 'Human Resources',
 'Collaboration',
 'Visualization (Computer Graphics)',
 'Data Visualization',
 'Statistical Tests',
 'Communication',
 'Culture',
 'Communication',
 'Culture',
 'Human Learning',
 'Strategy',
 'Planning',
 'Writing',
 'Mergers & Acquisitions',
 'Communication',
 'Culture',
 'Writing',
 'Culture',
 'Communication',
 'Critical Thinking',
 'Human Learning',
 'Planning',
 'Strategy',
 'Mergers & Acquisitions',
 'Human Learning',
 'Planning',
 'Strategy',
 'Mergers & Acquisitions',
 'Communication',
 'Entrepreneurship',
 'Business Analysis',
 'Market Research',
 'Planning',
 'Marketing',
 'Business Development',
 'Decision Making',
 'cial Media',
 'Writing',
 'Communication',
 'Communication',
 'Writing',
 'Writing',
 'Journalism',
 'Business Communication',
 'Communication',
 'Leadership and Management',
 'Strategy',
 'Critical Thinking',
 'Sales',
 'Writing',
 'Business Analysis',
 'Finance',
 'Marketing',
 'Problem Solving',
 'Entrepreneurship',
 'Negotiation',
 'Financial Management',
 'People Analysis',
 'Performance Management',
 'User Experience',
 'Collaboration',
 'Culture',
 'Culture',
 'Culture',
 'Business Communication',
 'Writing',
 'Business Development',
 'Business Intelligence',
 'Business Process Management',
 'Critical Thinking',
 'Leadership and Management',
 'Organizational Development',
 'Professional Development',
 'Business Communication',
 'Writing',
 'Business Development',
 'Business Intelligence',
 'Business Process Management',
 'Critical Thinking',
 'Leadership and Management',
 'Organizational Development',
 'Professional Development',
 'Communication',
 'Writing',
 'trategy',
 'Writing',
 'trategy',
 'Writing',
 'trategy',
 'Writing',
 'trategy',
 'Writing',
 'trategy',
 'Writing',
 'Culture',
 'Writing',
 'Writing',
 'Business Communication',
 'Organizational Development',
 'Business Intelligence',
 'Leadership and Management',
 'People Management',
 'Planning',
 'Project Management',
 'Writing',
 'Strategy',
 'Business Communication',
 'Organizational Development',
 'Business Intelligence',
 'Leadership and Management',
 'People Management',
 'Planning',
 'Project Management',
 'Writing',
 'Strategy',
 'Communication',
 'Culture',
 'Communication',
 'Culture',
 'Communication',
 'Culture',
 'Writing',
 'Planning',
 'Writing',
 'Writing',
 'Writing',
 'Writing',
 'Business Communication',
 'Communication',
 'Leadership and Management',
 'Writing',
 'Business Communication',
 'Communication',
 'Leadership and Management',
 'Writing',
 'Business Communication',
 'Communication',
 'Leadership and Management',
 'Writing',
 'Writing',
 'Communication',
 'Writing',
 'Communication',
 'Writing',
 'Communication',
 'Writing',
 'Communication',
 'Big Data',
 'Big Data',
 'Big Data',
 'Planning',
 'Planning',
 'Planning',
 'Communication',
 'Basic Descriptive Statistics',
 'Professional Development',
 'Data Analysis',
 'Data Visualization',
 'Planning',
 'Strategy',
 'Visualization (Computer Graphics)',
 'Statistical Tests',
 'Communication',
 'Basic Descriptive Statistics',
 'Professional Development',
 'Data Analysis',
 'Data Visualization',
 'Planning',
 'Strategy',
 'Visualization (Computer Graphics)',
 'Statistical Tests',
 'Business Communication',
 'Business Development',
 'Business Intelligence',
 'Communication',
 'Human Resources',
 'Negotiation',
 'People Analysis',
 'Professional Development',
 'Public Relations',
 'Writing',
 'Communication',
 'Communication',
 'Writing',
 'Writing',
 'Writing',
 'Writing',
 'Writing',
 'Communication',
 'Writing',
 'Communication',
 'Writing',
 'Writing',
 'Planning',
 'Planning',
 'Planning',
 'Planning',
 'Human Learning',
 'Writing',
 'Writing',
 'Writing',
 'Writing',
 'Culture',
 'Culture',
 'Culture',
 'Culture',
 'Communication',
 'Writing',
 'Business Communication',
 'Professional Development',
 'Writing',
 'Writing',
 'Writing',
 'Writing',
 'Writing',
 'Writing',
 'Business Communication',
 'Professional Development',
 'trategy',
 'Business Communication',
 'Negotiation',
 'Planning',
 'Customer Relationship Management',
 'Decision Making',
 'People Management',
 'Writing',
 'Collaboration',
 'Business Communication',
 'Communication',
 'Writing',
 'Leadership and Management',
 'Communication',
 'Writing',
 'Communication',
 'Communication',
 'Communication',
 'Culture',
 'Business Communication',
 'Communication',
 'Business Intelligence',
 'People Analysis',
 'Writing',
 'Account Management',
 'Critical Thinking',
 'Customer Analysis',
 'Human Learning',
 'Strategy',
 'Writing',
 'Writing',
 'Writing',
 'Writing',
 'Writing',
 'Communication',
 'Sales',
 'Critical Thinking',
 'People Analysis',
 'Problem Solving',
 'User Experience',
 'Communication',
 'Culture',
 'trategy',
 'Writing',
 'trategy',
 'Writing',
 'trategy',
 'Writing',
 'trategy',
 'Writing',
 'Writing',
 'Writing',
 'Business Communication',
 'Communication',
 'Decision Making',
 'Leadership and Management',
 'Strategy',
 'Adaptability',
 'Problem Solving',
 'Writing',
 'Conflict Management',
 'Professional Development',
 'Business Communication',
 'Communication',
 'Decision Making',
 'Leadership and Management',
 'Strategy',
 'Adaptability',
 'Problem Solving',
 'Writing',
 'Conflict Management',
 'Professional Development',
 'Communication',
 'Writing',
 'Leadership and Management',
 'Communication',
 'Writing',
 'Leadership and Management',
 'Writing',
 'Human Learning',
 'Planning',
 'trategy',
 'Writing',
 'trategy',
 'Writing',
 'trategy',
 'Writing',
 'trategy',
 'Writing',
 'Writing',
 'Communication',
 'Professional Development',
 'Writing',
 'Professional Development',
 'Writing',
 'Professional Development',
 'Writing',
 'Professional Development',
 'Writing',
 'Professional Development',
 'Writing',
 'trategy',
 'Writing',
 'Writing',
 'Communication',
 'Communication',
 'Leadership and Management',
 'Business Communication',
 'People Management',
 'Business Process Management',
 'Human Resources',
 'Leadership Development',
 'Strategy',
 'Business Development',
 'Human Learning',
 'Marketing',
 'Human Resources Operations',
 'Marketing Management',
 'Organizational Development',
 'Performance Management',
 'Planning',
 'Communication',
 'Culture',
 'Leadership and Management',
 'Communication',
 'Culture',
 'Leadership and Management',
 'Communication',
 'Collaboration',
 'Critical Thinking',
 'Communication',
 'Business Communication',
 'Culture',
 'Marketing',
 'Leadership and Management',
 'Communication',
 'Writing',
 'Communication',
 'Communication',
 'Writing',
 'Writing',
 'Writing',
 'Business Communication',
 'Writing',
 'Critical Thinking',
 'People Analysis',
 'Professional Development',
 'Business Intelligence',
 'Business Process Management',
 'Leadership and Management',
 'Marketing Design',
 'Writing',
 'Business Communication',
 'Communication',
 'Finance',
 'Business Analysis',
 'Negotiation',
 'Critical Thinking',
 'Financial Management',
 'Performance Management',
 'Business Communication',
 'Communication',
 'Finance',
 'Business Analysis',
 'Negotiation',
 'Critical Thinking',
 'Financial Management',
 'Performance Management',
 'Business Communication',
 'Communication',
 'Finance',
 'Business Analysis',
 'Negotiation',
 'Critical Thinking',
 'Financial Management',
 'Performance Management',
 'Business Communication',
 'Communication',
 'Finance',
 'Business Analysis',
 'Negotiation',
 'Critical Thinking',
 'Financial Management',
 'Performance Management',
 'Business Communication',
 'Communication',
 'Finance',
 'Business Analysis',
 'Negotiation',
 'Critical Thinking',
 'Financial Management',
 'Performance Management',
 'Business Communication',
 'Communication',
 'Finance',
 'Business Analysis',
 'Negotiation',
 'Critical Thinking',
 'Financial Management',
 'Performance Management',
 'Communication',
 'Leadership and Management',
 'Business Analysis',
 'Business Communication',
 'Finance',
 'Negotiation',
 'Business Development',
 'Business Psychology',
 'Leadership Development',
 'Problem Solving',
 'Communication',
 'Leadership and Management',
 'Business Analysis',
 'Business Communication',
 'Finance',
 'Negotiation',
 'Business Development',
 'Business Psychology',
 'Leadership Development',
 'Problem Solving',
 'Writing',
 'Writing',
 'Writing',
 'Business Communication',
 'Communication',
 'Leadership and Management',
 'Strategy',
 'Business Development',
 'Leadership Development',
 'Business Process Management',
 'Human Learning',
 'Organizational Development',
 'People Management',
 'Business Communication',
 'Business Communication',
 'Business Communication',
 'Business Communication',
 'Communication',
 'Writing',
 'Marketing',
 'Communication',
 'Business Communication',
 'Leadership and Management',
 'People Management',
 'Business Process Management',
 'Human Resources',
 'Human Resources Operations',
 'Marketing',
 'Marketing Management',
 'Performance Management',
 'Communication',
 'Business Communication',
 'Leadership and Management',
 'People Management',
 'Business Process Management',
 'Human Resources',
 'Human Resources Operations',
 'Marketing',
 'Marketing Management',
 'Performance Management',
 'Writing',
 'Writing',
 'Writing',
 'Communication',
 'Leadership and Management',
 'Writing',
 'Business Communication',
 'Culture',
 'Communication',
 'Marketing',
 'Decision Making',
 'Sales',
 'Business Psychology',
 'Leadership and Management',
 'People Analysis',
 'Customer Relationship Management',
 'Market Analysis',
 'Marketing Design',
 'Strategy',
 'Communication',
 'Business Communication',
 'Communication',
 'Planning',
 'Writing',
 'Communication',
 'Communication',
 'Communication',
 'Communication',
 'Leadership and Management',
 'Planning',
 'Communication',
 'Culture',
 'Culture',
 'Communication',
 'Writing',
 'Natural Language Processing',
 'Reinforcement Learning',
 'Culture',
 'Communication',
 'Writing',
 'Natural Language Processing',
 'Reinforcement Learning',
 'Culture',
 'Communication',
 'Writing',
 'Natural Language Processing',
 'Reinforcement Learning',
 'Culture',
 'Communication',
 'Writing',
 'Natural Language Processing',
 'Reinforcement Learning',
 'Culture',
 'Communication',
 'Writing',
 'Natural Language Processing',
 'Reinforcement Learning',
 'Leadership and Management',
 'Leadership and Management',
 'Leadership and Management',
 'Leadership and Management',
 'Algebra',
 'Calculus',
 'Problem Solving',
 'Computational Logic',
 'Mathematics',
 'Programming Principles',
 'Leadership and Management',
 'Leadership and Management',
 'Leadership and Management',
 'Leadership and Management',
 'Culture',
 'Algebra',
 'Calculus',
 'Communication',
 'Problem Solving',
 'Computational Logic',
 'Mathematics',
 'Writing',
 'Natural Language Processing',
 'Programming Principles',
 'Reinforcement Learning']

In [51]:
skills_frequency = Counter(skills)

In [52]:
skills_frequency

Counter({'Writing': 114,
         'Communication': 91,
         'Business Communication': 42,
         'Leadership and Management': 36,
         'Culture': 33,
         'Planning': 23,
         'Professional Development': 17,
         'Strategy': 16,
         'Critical Thinking': 15,
         'trategy': 15,
         'Negotiation': 13,
         'People Management': 10,
         'Business Development': 10,
         'Business Analysis': 10,
         'Performance Management': 10,
         'Business Intelligence': 9,
         'Finance': 9,
         'Organizational Development': 8,
         'People Analysis': 8,
         'Human Learning': 8,
         'Marketing': 8,
         'Problem Solving': 8,
         'Human Resources': 7,
         'Decision Making': 7,
         'Financial Management': 7,
         'Business Process Management': 7,
         'Natural Language Processing': 6,
         'Reinforcement Learning': 6,
         'Collaboration': 5,
         'Human Resources Operations': 4,
         'Project Management': 4,
         'Customer Relationship Management': 4,
         'Basic Descriptive Statistics': 4,
         'Data Analysis': 4,
         'Visualization (Computer Graphics)': 4,
         'Data Visualization': 4,
         'Statistical Tests': 4,
         'Leadership Development': 4,
         'Research and Design': 3,
         'Visual Design': 3,
         'Public Relations': 3,
         'Mergers & Acquisitions': 3,
         'Sales': 3,
         'Big Data': 3,
         'Marketing Management': 3,
         'Business Psychology': 3,
         'Entrepreneurship': 2,
         'User Experience': 2,
         'Adaptability': 2,
         'Conflict Management': 2,
         'Marketing Design': 2,
         'Algebra': 2,
         'Calculus': 2,
         'Computational Logic': 2,
         'Mathematics': 2,
         'Programming Principles': 2,
         'Application Development': 1,
         'Market Research': 1,
         'cial Media': 1,
         'Journalism': 1,
         'Account Management': 1,
         'Customer Analysis': 1,
         'Market Analysis': 1})

In [53]:
refined_data["Writing"] = 0
refined_data["Communication"] = 0
refined_data["Business Communication"] = 0
refined_data["Leadership and Management"] = 0
refined_data["Culture"] = 0
refined_data["Planning"] = 0
refined_data["Strategy"] = 0
refined_data["Critical Thinking"] = 0
refined_data["Professional Development"] = 0
refined_data["Others"] = 0

In [54]:
refined_data

,institution_name,title_of_course,star_ratings,number_of_raters,level,duration,skills_list,Writing,Communication,Business Communication,Leadership and Management,Culture,Planning,Strategy,Critical Thinking,Professional Development,Others
0,University of Pennsylvania,English for Career Development,4.8,15000.0,Mixed,1 - 3 Months,"Business Communication, Critical Thinking, Hum...",0,0,0,0,0,0,0,0,0,0
1,École Polytechnique,Étudier en France: French Intermediate course ...,4.8,4700.0,Intermediate,1 - 3 Months,"Communication, Culture, Writing",0,0,0,0,0,0,0,0,0,0
2,Yonsei University,First Step Korean,4.9,49000.0,Beginner,1 - 3 Months,"Communication, Culture, Writing",0,0,0,0,0,0,0,0,0,0
3,Georgia Institute of Technology,Lesson | Small Talk & Conversational Vocabulary,4.2,956000.0,Mixed,1 - 4 Weeks,"Communication, Culture, Writing",0,0,0,0,0,0,0,0,0,0
4,Peking University,Chinese for Beginners,4.8,19000.0,Mixed,1 - 3 Months,Communication,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,Arizona State University,商务英语课程:财经英语 Finance & Economics,4.8,10000.0,Intermediate,1 - 3 Months,Leadership and Management,0,0,0,0,0,0,0,0,0,0
207,"University of California, Irvine",Teaching Intermediate Grammar Project,4.4,10000.0,Intermediate,1 - 3 Months,Leadership and Management,0,0,0,0,0,0,0,0,0,0
208,Arizona State University,Proyecto Final: Chino básico - Lenguaje y cult...,4.4,7000.0,Mixed,1 - 3 Months,Leadership and Management,0,0,0,0,0,0,0,0,0,0
209,Arizona State University,总计划案 Final Project,4.7,257500.0,Intermediate,1 - 3 Months,Leadership and Management,0,0,0,0,0,0,0,0,0,0
210,Arizona State University,Chino básico: Lenguaje y cultura empresarial,4.5,508000.0,Beginner,3 - 6 Months,"Culture, Algebra, Calculus, Communication, Pro...",0,0,0,0,0,0,0,0,0,0

In [55]:
skills_split = refined_data["skills_list"].str.split(',')

In [56]:
for i in range(refined_data.shape[0]):
    tokens = skills_split.iloc[i]
    for j in tokens:
        print(type(j))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

In [57]:
for i in range(refined_data.shape[0]):
    tokens = skills_split.iloc[i]
    for j in tokens:
        if((j == "Writing") | (j == " Writing")):
            refined_data.iloc[i,7] = 1
        elif((j == "Communication") | (j == " Communication")):
            refined_data.iloc[i,8] = 1
        elif((j == "Business Communication") | (j == " Business Communication")):
            refined_data.iloc[i,9] = 1
        elif((j == "Leadership and Management") | (j == " Leadership and Management")):
            refined_data.iloc[i,10] = 1
        elif((j == "Culture") | (j == " Culture")):
            refined_data.iloc[i,11] = 1
        elif((j == "Planning") | (j == " Planning")):
            refined_data.iloc[i,12] = 1
        elif((j == "Strategy") | (j == " Strategy")):
            refined_data.iloc[i,13] = 1
        elif((j == "Critical Thinking") | (j == " Critical Thinking")):
            refined_data.iloc[i,14] = 1
        elif((j == "Professional Development") | (j == " Professional Development")):
            refined_data.iloc[i,15] = 1
        else:
            refined_data.iloc[i,16] = 1

In [58]:
refined_data

,institution_name,title_of_course,star_ratings,number_of_raters,level,duration,skills_list,Writing,Communication,Business Communication,Leadership and Management,Culture,Planning,Strategy,Critical Thinking,Professional Development,Others
0,University of Pennsylvania,English for Career Development,4.8,15000.0,Mixed,1 - 3 Months,"Business Communication, Critical Thinking, Hum...",0,0,1,0,0,0,0,1,0,1
1,École Polytechnique,Étudier en France: French Intermediate course ...,4.8,4700.0,Intermediate,1 - 3 Months,"Communication, Culture, Writing",1,1,0,0,1,0,0,0,0,0
2,Yonsei University,First Step Korean,4.9,49000.0,Beginner,1 - 3 Months,"Communication, Culture, Writing",1,1,0,0,1,0,0,0,0,0
3,Georgia Institute of Technology,Lesson | Small Talk & Conversational Vocabulary,4.2,956000.0,Mixed,1 - 4 Weeks,"Communication, Culture, Writing",1,1,0,0,1,0,0,0,0,0
4,Peking University,Chinese for Beginners,4.8,19000.0,Mixed,1 - 3 Months,Communication,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,Arizona State University,商务英语课程:财经英语 Finance & Economics,4.8,10000.0,Intermediate,1 - 3 Months,Leadership and Management,0,0,0,1,0,0,0,0,0,0
207,"University of California, Irvine",Teaching Intermediate Grammar Project,4.4,10000.0,Intermediate,1 - 3 Months,Leadership and Management,0,0,0,1,0,0,0,0,0,0
208,Arizona State University,Proyecto Final: Chino básico - Lenguaje y cult...,4.4,7000.0,Mixed,1 - 3 Months,Leadership and Management,0,0,0,1,0,0,0,0,0,0
209,Arizona State University,总计划案 Final Project,4.7,257500.0,Intermediate,1 - 3 Months,Leadership and Management,0,0,0,1,0,0,0,0,0,0
210,Arizona State University,Chino básico: Lenguaje y cultura empresarial,4.5,508000.0,Beginner,3 - 6 Months,"Culture, Algebra, Calculus, Communication, Pro...",1,1,0,0,1,0,0,0,0,1

In [59]:
refined_data.drop("skills_list", axis=1, inplace=True)

In [60]:
refined_data.isnull().sum()

institution_name             0
title_of_course              0
star_ratings                 0
number_of_raters             0
level                        0
duration                     0
Writing                      0
Communication                0
Business Communication       0
Leadership and Management    0
Culture                      0
Planning                     0
Strategy                     0
Critical Thinking            0
Professional Development     0
Others                       0
dtype: int64

In [61]:
refined_data.shape

(211, 16)

## Converting the processed data frame to a .csv file

In [62]:
csv_file = "refined_data_set.csv"

In [63]:
refined_data.to_csv(csv_file, index=False)